export const translations = {
  es: {
    accessibility: {
      title: 'Accesibilidad',
      openPanel: 'Abrir panel de accesibilidad',
      closePanel: 'Cerrar panel',
      darkMode: {
        title: 'Contraste Oscuro',
        description: 'Activar modo oscuro',
        active: 'Activado',
        inactive: 'Desactivado',
      },
      fontSize: {
        title: 'Tamaño de Texto',
        description: 'Ajustar tamaño de fuente',
        increase: 'Aumentar tamaño de texto',
        decrease: 'Disminuir tamaño de texto',
      },
      highContrast: {
        title: 'Alto Contraste',
        description: 'Modo de alto contraste',
        active: 'Activado',
        inactive: 'Desactivado',
      },
      grayscale: {
        title: 'Escala de Grises',
        description: 'Activar filtro de escala de grises',
        active: 'Activado',
        inactive: 'Desactivado',
      },
      largeCursor: {
        title: 'Cursor Grande',
        description: 'Activar cursor grande',
        active: 'Activado',
        inactive: 'Desactivado',
      },
      language: {
        title: 'Idioma',
        description: 'Cambiar idioma',
        spanish: 'Español',
        quechua: 'Quechua',
      },
      textToSpeech: {
        title: 'Escuchar',
        description: 'Leer contenido en voz alta',
        start: 'Iniciar lectura',
        stop: 'Detener lectura',
      },
      reset: {
        title: 'Restablecer Configuración',
        description: 'Restaurar valores por defecto',
      },
    },
    home: {
      title: 'Plataforma Informativa Electoral',
      subtitle: 'Elecciones Perú 2026',
      carousel: {
        slide1: {
          title: 'Prepárate para las Elecciones 2026',
          subtitle: 'Toda la información que necesitas para ejercer tu derecho al voto de manera informada. Conoce a los candidatos, encuentra tu local de votación y mantente actualizado con el proceso electoral.',
          badge: 'Elecciones Generales Perú',
          buttonCandidates: 'Ver Candidatos',
          buttonCalendar: 'Ver Calendario',
        },
        slide2: {
          title: 'Participa y decide el futuro',
          subtitle: 'Infórmate sobre el proceso electoral, los partidos y los candidatos. Tu voto es tu voz.',
          badge: 'Elecciones Generales Perú',
          buttonCandidates: 'Ver Candidatos',
          buttonCalendar: 'Ver Calendario',
        },
        slide3: {
          title: 'Conoce a los partidos políticos',
          subtitle: 'Descubre las propuestas y candidatos de cada organización política. Infórmate y elige con criterio.',
          badge: 'Partidos Políticos 2026',
          buttonCandidates: 'Ver Candidatos',
          buttonCalendar: 'Ver Calendario',
        },
        slide4: {
          title: 'Tu voto es importante',
          subtitle: 'Ejerce tu derecho democrático y participa en el futuro del país. Encuentra tu local de votación.',
          badge: 'Vota Informado',
          buttonCandidates: 'Ver Candidatos',
          buttonCalendar: 'Ver Calendario',
        },
      },
      hero: {
        badge: 'Elecciones Generales Perú',
        title: 'Prepárate para las',
        titleHighlight: 'Elecciones 2026',
        description: 'Toda la información que necesitas para ejercer tu derecho al voto de manera informada. Conoce a los candidatos, encuentra tu local de votación y mantente actualizado con el proceso electoral.',
        viewCandidates: 'Ver Candidatos',
        viewCalendar: 'Ver Calendario',
      },
      quickAccess: {
        title: 'Accesos Rápidos',
        subtitle: 'Accede rápidamente a la información más importante',
        whereToVote: {
          title: 'Dónde Votar',
          description: 'Consulta tu centro de votación con tu DNI',
        },
        candidates: {
          title: 'Candidatos',
          description: 'Conoce a los precandidatos presidenciales',
        },
        calendar: {
          title: 'Calendario Electoral',
          description: 'Fechas importantes del proceso electoral',
        },
        guide: {
          title: 'Guía Miembros de Mesa',
          description: 'Todo lo que necesitas saber si eres miembro',
        },
      },
      infoBanner: {
        title: '¿Primera vez votando?',
        description: 'Aprende todo sobre el proceso electoral peruano y cómo ejercer tu voto de manera correcta.',
        link: 'Ver guía completa',
      },
    },
    countdown: {
      title: 'Faltan para las Elecciones',
      days: 'DÍAS',
      hours: 'HORAS',
      minutes: 'MINUTOS',
      seconds: 'SEGUNDOS',
      short: {
        label: 'Faltan:',
        days: 'días',
        hours: 'hrs',
        minutes: 'min',
        seconds: 'seg',
      },
    },
    navbar: {
      home: 'Inicio',
      candidates: 'Candidatos',
      calendar: 'Calendario',
      whereToVote: 'Dónde Voto',
      guideElector: 'Guía del Elector',
      guideMembers: 'Guía Miembros',
    },
    footer: {
      brand: {
        title: 'Elecciones 2026',
        description: 'Plataforma informativa para las Elecciones Generales del Perú 2026. Mantente informado y ejerce tu derecho al voto de manera responsable.',
      },
      information: {
        title: 'Información',
        candidates: 'Candidatos 2026',
        calendar: 'Calendario Electoral',
        whereToVote: 'Dónde Votar',
        proposals: 'Propuestas',
      },
      resources: {
        title: 'Recursos',
        guideMembers: 'Guía Miembros de Mesa',
        faq: 'Preguntas Frecuentes',
        news: 'Noticias',
        onpeOfficial: 'ONPE Oficial',
      },
      legal: {
        title: 'Legal',
        terms: 'Términos de Uso',
        privacy: 'Política de Privacidad',
        contact: 'Contacto',
        about: 'Sobre Nosotros',
      },
      bottom: {
        copyright: 'Elecciones 2026. Proyecto desarrollado para Hackathon El Comercio.',
        disclaimer: 'Esta es una plataforma informativa no oficial. Para información oficial, visita',
      },
    },
    calendar: {
      title: 'Cronograma Electoral',
      pagination: {
        previous: 'Grupo anterior',
        next: 'Siguiente grupo',
        of: 'de',
      },
      dateLabel: 'FECHA',
      events: {
        primaryAffiliates: 'Primarias (afiliados y no afiliados)',
        primaryDelegates: 'Primarias (delegados)',
        generalElectionsFirst: 'Elecciones generales (primera vuelta)',
        secondRound: 'Segunda vuelta presidencial (si aplica)',
        allianceDeadline: 'Límite para solicitar alianzas electorales',
        allianceRegistration: 'Límite para inscribir alianzas en el ROP',
        electoralRollClosure: 'Cierre del padrón electoral',
        finalRollApproval: 'Aprobación del padrón electoral definitivo',
        candidateRegistration: 'Fecha límite para inscribir fórmulas y listas de candidatos',
        candidateWithdrawal: 'Fin de plazo para renuncia/retiro de candidatos',
        challengesFirst: 'Fin para tachas y exclusiones (1ra instancia)',
        challengesAppeals: 'Fin de apelaciones por tachas/exclusiones',
        finalCandidates: 'Inscripción definitiva de candidaturas',
        legalExclusion: 'Último día para exclusión por situación jurídica',
        generalElections: 'Elecciones generales',
        secondRoundElection: 'Segunda vuelta presidencial (si aplica)',
        pollWorkersDraw: 'Sorteo de miembros de mesa',
        pollWorkersPublication: 'Publicación de seleccionados',
        pollWorkersTraining: 'Capacitaciones ONPE',
        pollTablesSetup: 'Instalación de mesas para primera vuelta',
      },
      dates: {
        nov30_2025: '30 de noviembre de 2025',
        dec7_2025: '7 de diciembre de 2025',
        apr12_2026: '12 de abril de 2026',
        jun7_2026: '7 de junio de 2026',
        aug2_2025: '2 de agosto de 2025',
        sep1_2025: '1 de septiembre de 2025',
        oct14_2025: '14 de octubre de 2025',
        dec13_2025: '13 de diciembre de 2025',
        dec23_2025: '23 de diciembre de 2025',
        feb11_2026: '11 de febrero de 2026',
        feb26_2026: '26 de febrero de 2026',
        mar13_2026: '13 de marzo de 2026',
        mar14_2026: '14 de marzo de 2026',
        apr11_2026: '11 de abril de 2026',
        feb1_2026: 'Hasta el 1 de febrero de 2026',
        feb_mar_2026: 'Febrero – marzo de 2026',
        training: 'Organización e instalación de mesas de sufragio',
      },
    },
    guideElector: {
      hero: {
        badge: 'Guía Oficial',
        title: 'Guía del',
        titleHighlight: 'Elector',
        description: 'Todo lo que necesitas saber para ejercer tu derecho al voto en las Elecciones Generales Perú 2026. Información oficial y resumida.',
      },
      tabs: {
        general: 'Información General',
        beforeVoting: 'Antes de Votar',
        votingProcess: 'Proceso de Votación',
        fines: 'Multas',
        prohibitions: 'Prohibiciones',
        recommendations: 'Recomendaciones',
      },
      general: {
        videoTitle: 'Video Instructivo ONPE',
        videoSubtitle: 'Aprende cómo separar tu cédula de votación correctamente',
        importantBallots: 'Importante sobre las cédulas',
        importantBallotsText: 'La cédula de votación se separa en secciones. Los miembros de la Policía Nacional y las Fuerzas Armadas recibirán una cédula especial diferente a la del resto de ciudadanos.',
        whatElected: '¿Qué se elige en 2026?',
        whatElectedSubtitle: 'Conoce los cargos por los que votarás',
        requirementsTitle: 'Requisitos para Votar',
        requirementsSubtitle: 'Verifica si estás apto para participar',
        documentsTitle: 'Documentos Válidos',
        documentsSubtitle: 'Solo estos documentos son aceptados',
      },
      positions: {
        president: 'Presidente y Vicepresidentes',
        presidentDesc: 'Elegimos al Presidente de la República y sus dos vicepresidentes.',
        deputies: 'Cámara de Diputados',
        deputiesDesc: 'Representantes por cada departamento del país.',
        senators: 'Cámara de Senadores',
        senatorsDesc: 'Senadores nacionales y regionales.',
        andean: 'Parlamento Andino',
        andeanDesc: 'Representantes peruanos ante el organismo supranacional andino.',
      },
      requirements: {
        req1: 'Ser mayor de 18 años',
        req2: 'Estar inscrito en el padrón electoral',
        req3: 'Pueden votar peruanos en Perú y en el extranjero',
        req4: 'Voto obligatorio hasta los 70 años',
        req5: 'Voto opcional después de los 70 años',
      },
      documents: {
        blueDNI: 'DNI Azul',
        blueDNIDesc: 'Documento Nacional de Identidad tradicional',
        electronicDNI: 'DNI Electrónico',
        electronicDNIDesc: 'Versión moderna del DNI con chip',
        yellowDNI: 'DNI Amarillo',
        yellowDNIDesc: 'Para extranjeros residentes',
        notValid: 'NO válidos',
        notValidDesc: 'Pasaporte ni Licencia de conducir',
      },
      beforeVoting: {
        whereVoteTitle: '¿Dónde Votar?',
        whereVoteSubtitle: 'Consulta tu local de votación con anticipación',
        channelsTitle: 'Canales de consulta',
        channelsText: 'Puedes consultar tu local de votación en:',
        website: 'Página web:',
        mobileApp: 'App móvil:',
        whatsapp: 'WhatsApp:',
        whatsappText: 'Servicio de consulta ONPE',
        importantInfo: 'Información importante',
        importantInfoText: 'Al consultar tu local encontrarás: nombre del local, número de mesa, número de orden y pabellón. Anota esta información o toma captura de pantalla.',
        whatBringTitle: '¿Qué Llevar el Día de la Votación?',
        whatBringSubtitle: 'Prepara estos elementos antes de salir',
        dniRequired: 'DNI (Obligatorio)',
        dniRequiredDesc: 'Tu Documento Nacional de Identidad es indispensable para votar.',
        penOptional: 'Lapicero azul (Opcional)',
        penOptionalDesc: 'La ONPE entrega lapiceros, pero puedes llevar el tuyo.',
        maskOptional: 'Mascarilla (Si aplica)',
        maskOptionalDesc: 'Si existiera recomendación sanitaria vigente.',
      },
      votingProcess: {
        title: 'Proceso de Votación',
        subtitle: 'Sigue estos pasos en orden',
        step1: 'Ubicar tu mesa de votación',
        step2: 'Hacer cola correspondiente',
        step3: 'Presentar tu DNI al miembro de mesa',
        step4: 'Firmar el padrón electoral',
        step5: 'Recibir la cédula de votación',
        step6: 'Ingresar a la cabina secreta',
        step7: 'Marcar tu voto',
        step8: 'Depositar cédula en el ánfora',
        step9: 'Recibir tinta indeleble en el dedo',
        step10: 'Recibir constancia de votación (si aplica)',
      },
      fines: {
        notVotingTitle: 'Multas por No Votar',
        notVotingSubtitle: 'Según clasificación del distrito',
        extremePoor: 'Pobre extremo',
        nonExtremePoor: 'Pobre no extremo',
        notPoor: 'No pobre',
        memberTitle: 'Multas para Miembros de Mesa',
        memberSubtitle: 'Incumplimiento de funciones',
        notAttend: 'No asistir como miembro de mesa',
        leaveEarly: 'Retirarse antes de culminar',
      },
      prohibitions: {
        title: 'Prohibiciones',
        subtitle: 'Acciones que están prohibidas',
        proh1: 'Grabar o tomar fotos dentro de la cabina de votación',
        proh2: 'Mostrar tu voto a otras personas',
        proh3: 'Hacer propaganda electoral en el local',
        proh4: 'Suplantar identidad de otra persona',
        proh5: 'Ingresar al local con símbolos partidarios',
        proh6: 'Alterar el orden en el local de votación',
      },
      recommendations: {
        title: 'Recomendaciones',
        subtitle: 'Consejos para una mejor experiencia',
        arriveEarly: 'Llegar temprano',
        arriveEarlyDesc: 'Evita las aglomeraciones y tendrás más tiempo.',
        checkDNI: 'Revisa tu DNI',
        checkDNIDesc: 'Verifica días antes que tu documento esté en buen estado.',
        noPropaganda: 'No lleves propaganda',
        noPropagandaDesc: 'Está prohibido ingresar con símbolos o publicidad política.',
        askHelp: 'Pide ayuda si tienes dudas',
        askHelpDesc: 'Los miembros de mesa están para orientarte.',
        priority: 'Prioridad especial',
        priorityDesc: 'Embarazadas, adultos mayores y personas con discapacidad tienen prioridad.',
        checkLocation: 'Consulta tu local con anticipación',
        checkLocationDesc: 'Ubica tu local de votación días antes en www.onpe.gob.pe',
      },
    },
    dondeVotar: {
      title: '¿Dónde Voto?',
      subtitle: 'Encuentra tu centro de votación con tu DNI',
      search: {
        label: 'Ingresa tu DNI (8 dígitos)',
        placeholder: '12345678',
        button: 'Buscar',
        searching: 'Buscando...',
      },
      success: 'Centro de votación encontrado',
      errors: {
        invalidLength: 'Por favor, ingrese un DNI válido de 8 dígitos',
        onlyNumbers: 'El DNI solo debe contener números',
        notFound: 'No se encontró información para el DNI ingresado. Verifique el número e intente nuevamente.',
        searchError: 'Error al buscar la información. Por favor, intente nuevamente.',
      },
      result: {
        votingCenter: 'Centro de Votación',
        fullName: 'Nombre Completo',
        table: 'Mesa',
        district: 'Distrito',
        address: 'Dirección',
        department: 'Departamento',
        location: 'Ubicación',
        viewMap: 'Ver en Google Maps',
        getDirections: 'Llegar con Google Maps',
        transport: {
          title: 'Cómo Llegar',
          reference: 'Referencia',
          routes: 'Rutas disponibles',
          approxTime: 'Tiempo aproximado',
          noInfo: 'No hay información de transporte disponible',
        },
        schedule: {
          label: 'Horario de votación',
          time: '7:00 AM - 5:00 PM',
        },
      },
      tips: {
        title: '¿Cómo funciona?',
        step1: 'Ingresa tu número de DNI (8 dígitos) en el campo de búsqueda',
        step2: 'Haz clic en "Buscar" para encontrar tu centro de votación',
        step3: 'Revisa la información de tu mesa y ubicación',
        step4: 'Usa "Ver Ruta" para obtener indicaciones de cómo llegar',
      },
      infoCards: {
        instructions: {
          title: 'Instrucciones para Votar',
          items: [
            'Lleva tu DNI original y en buen estado',
            'No uses ropa con logos políticos',
            'Llega temprano para evitar aglomeraciones',
            'Respeta las indicaciones de los miembros de mesa',
          ],
        },
        security: {
          title: 'Seguridad',
          items: [
            'No compartas tu DNI con desconocidos',
            'Verifica que estés en el centro correcto',
            'Reporta cualquier irregularidad a las autoridades',
            'No lleves objetos prohibidos al centro de votación',
          ],
        },
        transport: {
          title: 'Transporte',
          publicAvailable: 'Transporte público disponible',
          taxiAvailable: 'Servicio de taxi disponible en la zona',
        },
      },
      quiz: {
        title: 'Quiz para Electores',
        button: 'Quiz para Electores',
        previous: 'Anterior',
        next: 'Siguiente',
        questionOf: 'Pregunta',
        of: 'de',
        viewResults: 'Ver resultados',
        excellent: '¡Excelente! Todas tus respuestas son correctas.',
        correctAnswers: 'Respuestas correctas:',
        questions: [
          {
            question: '¿Qué documento necesitas para votar?',
            options: ['Carné universitario', 'Pasaporte', 'Identidad digital', 'DNI (vigente o caducado)'],
            answer: 3,
          },
          {
            question: '¿Cuál es el horario oficial de votación?',
            options: ['6:00 a.m. – 3:00 p.m.', '7:00 a.m. – 5:00 p.m.', '8:00 a.m. – 6:00 p.m.', '9:00 a.m. – 4:00 p.m.'],
            answer: 1,
          },
          {
            question: '¿Cuál es la consecuencia de no votar si vives en un distrito "no pobre"?',
            options: ['Sin sanción', 'Multa de S/ 46', 'Multa de S/ 92', 'Multa de S/ 120'],
            answer: 2,
          },
          {
            question: '¿Cuántos votos preferenciales puedes marcar para Congreso?',
            options: ['Ninguno', 'Uno', 'Dos', 'Tres'],
            answer: 1,
          },
          {
            question: '¿Qué debes hacer si te equivocas al marcar la cédula?',
            options: ['Dejarla así y entregarla', 'Pedir una nueva cédula al presidente de mesa', 'Salir del local', 'Llamar a un fiscalizador'],
            answer: 1,
          },
        ],
      },
    },
    candidates: {
      title: 'Candidatos Presidenciales 2026',
      subtitle: 'Conoce a los precandidatos que aspiran a la presidencia',
      loading: 'Cargando candidatos',
      filters: {
        all: 'Todos',
        department: 'Departamento',
        ideology: 'Ideología',
        search: 'Buscar candidato...',
        clear: 'Limpiar filtros',
      },
      card: {
        viewDetails: 'Ver Detalles',
        compare: 'Comparar',
        party: 'Partido',
        ideology: 'Ideología',
        department: 'Departamento',
      },
      noResults: 'No se encontraron candidatos con los filtros seleccionados',
    },
    guideMembers: {
      title: 'Guía para Miembros de Mesa',
      subtitle: 'Información esencial para el día de las elecciones',
      hero: {
        badge: 'Guía Oficial',
        title: 'Guía para',
        titleHighlight: 'Miembros de Mesa',
        description: 'Todo lo que necesitas saber para cumplir con tu labor como miembro de mesa en las Elecciones Generales Perú 2026.',
      },
      tabs: {
        responsibilities: 'Responsabilidades',
        schedule: 'Horario',
        documents: 'Documentos',
        fines: 'Multas',
        training: 'Capacitación',
      },
      responsibilities: {
        title: 'Tus Responsabilidades',
        items: [
          'Llegar temprano al local de votación',
          'Verificar identidad de los electores',
          'Entregar cédulas de votación',
          'Supervisar el proceso de votación',
          'Contar votos al finalizar',
          'Firmar actas electorales',
        ],
      },
      schedule: {
        title: 'Horario del Día Electoral',
        arrival: 'Llegada al local: 6:00 AM',
        opening: 'Apertura de mesa: 7:00 AM',
        voting: 'Votación: 7:00 AM - 5:00 PM',
        counting: 'Conteo de votos: Después de las 5:00 PM',
      },
      fines: {
        title: 'Multas por Incumplimiento',
        notAttend: 'No asistir: S/ 230',
        leaveEarly: 'Retirarse antes: S/ 230',
        excuse: 'Justificación válida: Sin multa',
      },
      quiz: {
        title: 'Quiz para Miembros de Mesa',
        previous: 'Anterior',
        next: 'Siguiente',
        showResults: 'Ver resultados',
        perfect: '¡Excelente! Todas tus respuestas son correctas.',
        score: 'Respuestas correctas',
        of: 'de',
      },
    },
    chatbot: {
      title: 'Asistente Electoral',
      subtitle: 'Elecciones 2026',
      welcome: '¡Hola! 👋 Soy tu asistente virtual para las Elecciones 2026 de Perú. Puedo ayudarte con consultas sobre miembros de mesa, proceso de votación, candidatos, fechas importantes y más. ¿En qué puedo ayudarte? 🗳️',
      placeholder: 'Escribe tu pregunta sobre las elecciones...',
      typing: 'Escribiendo...',
      error: 'Lo siento, hubo un error al procesar tu mensaje. Por favor, intenta nuevamente. Si el problema persiste, verifica que el servidor esté funcionando.',
      helpText: 'Estoy aquí para ayudarte con información sobre las elecciones',
      open: 'Abrir chatbot - Asistente virtual para elecciones',
      close: 'Cerrar chatbot',
    },
  },
  qu: {
    accessibility: {
      title: 'Yanapay',
      openPanel: 'Yanapay panelta kichay',
      closePanel: 'Panelta wichqay',
      darkMode: {
        title: 'Yana Modo',
        description: 'Yana modota kichay',
        active: 'Kichasqa',
        inactive: 'Wichqasqa',
      },
      fontSize: {
        title: 'Qillqapa Hatun Kaynin',
        description: 'Qillqapa hatun kayninta allichay',
        increase: 'Qillqata hatunchay',
        decrease: 'Qillqata huch\'uyachiy',
      },
      highContrast: {
        title: 'Allin Rikukuy',
        description: 'Allin rikukuy modo',
        active: 'Kichasqa',
        inactive: 'Wichqasqa',
      },
      grayscale: {
        title: 'Uqi Llimp\'ikuna',
        description: 'Uqi llimp\'ikunaman tukuchiy',
        active: 'Kichasqa',
        inactive: 'Wichqasqa',
      },
      largeCursor: {
        title: 'Hatun Señalaq',
        description: 'Hatun señalaqta kichay',
        active: 'Kichasqa',
        inactive: 'Wichqasqa',
      },
      language: {
        title: 'Simi',
        description: 'Simita tikray',
        spanish: 'Kastilla Simi',
        quechua: 'Runasimi',
      },
      textToSpeech: {
        title: 'Uyariy',
        description: 'Qillqasqata uyariy',
        start: 'Uyariyta qallariy',
        stop: 'Uyariyta sayachiy',
      },
      reset: {
        title: 'Kutichinapaq',
        description: 'Tukuy imata ñawpaq hina ruway',
      },
    },
    home: {
      title: 'Akllanakuy Willana Plataforma',
      subtitle: 'Piruw 2026 Akllanakuna',
      carousel: {
        slide1: {
          title: 'Wakichikuy 2026 Akllanakuna kama',
          subtitle: 'Tukuy willakuykuna yachanapaq imaynatachus derechoykita allin akllanapaq. Riqsiy akllanaman riqkunata, tariykuy maypichus votanki, chaymanta yachaykuy akllanakuypa ruwayninmanta.',
          badge: 'Piruw Hatun Akllanakuna',
          buttonCandidates: 'Riqsiy Akllanaman Riqkunata',
          buttonCalendar: 'Qaway P\'unchawkunata',
        },
        slide2: {
          title: 'Yaykuy chaymanta akllay hamuq pachatawan',
          subtitle: 'Yachakuy akllanakuypa ruwayninmanta, partidokunamanta chaymanta candidatokunamanta. Votoyqa simiykimi.',
          badge: 'Piruw Hatun Akllanakuna',
          buttonCandidates: 'Riqsiy Akllanaman Riqkunata',
          buttonCalendar: 'Qaway P\'unchawkunata',
        },
        slide3: {
          title: 'Riqsiy partidokunamanta',
          subtitle: 'Yachay tukuy partidokunamanta, yuyaychakunamanta chaymanta candidatokunamanta. Yachakuy chaymanta allin akllay.',
          badge: 'Partidos Políticos 2026',
          buttonCandidates: 'Riqsiy Akllanaman Riqkunata',
          buttonCalendar: 'Qaway P\'unchawkunata',
        },
        slide4: {
          title: 'Votoyqa ancha allinmi',
          subtitle: 'Ruway derechoykita chaymanta yanapay suyunchikpa hamuq pachanta. Tariykuy maypichus votanki.',
          badge: 'Yachakuspa Votay',
          buttonCandidates: 'Riqsiy Akllanaman Riqkunata',
          buttonCalendar: 'Qaway P\'unchawkunata',
        },
      },
      hero: {
        badge: 'Piruw Hatun Akllanakuna',
        title: 'Wakichikuy',
        titleHighlight: '2026 Akllanakuna kama',
        description: 'Tukuy willakuykuna yachanapaq imaynatachus derechoykita allin akllanapaq. Riqsiy akllanaman riqkunata, tariykuy maypichus votanki, chaymanta yachaykuy akllanakuypa ruwayninmanta.',
        viewCandidates: 'Riqsiy Akllanaman Riqkunata',
        viewCalendar: 'Qaway P\'unchawkunata',
      },
      quickAccess: {
        title: 'Usqhaylla Yaykuna',
        subtitle: 'Usqhaylla yaykuy aswan chaniyuq willakuykunaman',
        whereToVote: {
          title: 'Maypi Akllasaq',
          description: 'Tariykuy maypi votanki DNI-ykiwan',
        },
        candidates: {
          title: 'Akllanaman Riqkuna',
          description: 'Riqsiy umalliq akllanaman riqkunata',
        },
        calendar: {
          title: 'Akllanakuypa Calendario',
          description: 'Chaniyuq p\'unchawkuna akllanakuypi',
        },
        guide: {
          title: 'Mesa Runakuna Yanapay',
          description: 'Tukuy imata yachay miembro kaspayki',
        },
      },
      infoBanner: {
        title: '¿Ñawpaq kutitaq votanki?',
        description: 'Yachay tukuy imata Piruwpa akllanakuyninmanta chaymanta imaynatachus allin votanapaq.',
        link: 'Qaway hunt\'asqa yanapayta',
      },
    },
    countdown: {
      title: 'Akllanakuna kama qhipanqa',
      days: 'P\'UNCHAWKUNA',
      hours: 'HORAKUNA',
      minutes: 'MINUTUKUNA',
      seconds: 'SEGUNDUKUNA',
      short: {
        label: 'Qhipanqa:',
        days: 'p\'nchw',
        hours: 'hrs',
        minutes: 'min',
        seconds: 'seg',
      },
    },
    navbar: {
      home: 'Qallariy',
      candidates: 'Akllanaman Riqkuna',
      calendar: 'P\'unchawkuna',
      whereToVote: 'Maypi Votay',
      guideElector: 'Akllaqpa Yanapay',
      guideMembers: 'Mesa Runakuna Yanapay',
    },
    footer: {
      brand: {
        title: 'Akllanakuna 2026',
        description: 'Piruw 2026 Hatun Akllanakuna kama willana plataforma. Allin yachaywan qipanakuy chaymanta derechoykita allin ruway votanapaq.',
      },
      information: {
        title: 'Willakuykuna',
        candidates: 'Akllanaman Riqkuna 2026',
        calendar: 'Akllanakuypa P\'unchawnin',
        whereToVote: 'Maypi Votay',
        proposals: 'Yuyaychaykuna',
      },
      resources: {
        title: 'Yanapaykuna',
        guideMembers: 'Mesa Runakuna Yanapay',
        faq: 'Sapa Kuti Tapukuykuna',
        news: 'Willakuykuna',
        onpeOfficial: 'ONPE Oficial',
      },
      legal: {
        title: 'Kamachikuy',
        terms: 'Llamk\'aypa Kamachiynin',
        privacy: 'Pakasqa Kay Kamachiy',
        contact: 'Rimanakunapaq',
        about: 'Ñuqaykumanta',
      },
      bottom: {
        copyright: 'Akllanakuna 2026. Proyecto ruwasqa Hackathon El Comercio kama.',
        disclaimer: 'Kayqa mana oficial willana plataforma. Oficial willakuypaq, watiqay',
      },
    },
    calendar: {
      title: 'Akllanakuypa P\'unchawnin',
      pagination: {
        previous: 'Ñawpaq qutu',
        next: 'Qhipantin qutu',
        of: 'manta',
      },
      dateLabel: 'P\'UNCHAW',
      events: {
        primaryAffiliates: 'Ñawpaq Akllanakuna (kuskasqakuna chaymanta mana kuskasqakuna)',
        primaryDelegates: 'Ñawpaq Akllanakuna (apachikunakuna)',
        generalElectionsFirst: 'Hatun Akllanakuna (ñawpaq kuti)',
        secondRound: 'Iskay kuti umalliq akllana (ruwakuptinqa)',
        allianceDeadline: 'Tukuy pacha tantanakuy akllanakuna mañanapaq',
        allianceRegistration: 'Tukuy pacha tantanakuykunata ROP-pi qillqanapaq',
        electoralRollClosure: 'Akllaqkunapa sutinpa wichqaynin',
        finalRollApproval: 'Akllaqkunapa tukuy sutinpa allinchay',
        candidateRegistration: 'Tukuy pacha candidatokunata chaymanta listata qillqanapaq',
        candidateWithdrawal: 'Tukuy pacha candidatokuna ripunanpaq',
        challengesFirst: 'Tukuy pacha tachakunapaq chaymanta hurqunapaq (ñawpaq)',
        challengesAppeals: 'Tukuy pacha apelacionkuna tachakunamanta',
        finalCandidates: 'Tukuy candidatokunapa qillqakuynin',
        legalExclusion: 'Qhipa p\'unchaw hurqunapaq kamachiy rayku',
        generalElections: 'Hatun Akllanakuna',
        secondRoundElection: 'Iskay kuti umalliq akllana (ruwakuptinqa)',
        pollWorkersDraw: 'Mesa runakunapa sorteonin',
        pollWorkersPublication: 'Akllasqakunapa willakuynin',
        pollWorkersTraining: 'ONPE yachachikuykuna',
        pollTablesSetup: 'Mesakunata churay ñawpaq kutipaq',
      },
      dates: {
        nov30_2025: '30 noviembre 2025',
        dec7_2025: '7 diciembre 2025',
        apr12_2026: '12 abril 2026',
        jun7_2026: '7 junio 2026',
        aug2_2025: '2 agosto 2025',
        sep1_2025: '1 septiembre 2025',
        oct14_2025: '14 octubre 2025',
        dec13_2025: '13 diciembre 2025',
        dec23_2025: '23 diciembre 2025',
        feb11_2026: '11 febrero 2026',
        feb26_2026: '26 febrero 2026',
        mar13_2026: '13 marzo 2026',
        mar14_2026: '14 marzo 2026',
        apr11_2026: '11 abril 2026',
        feb1_2026: '1 febrero 2026 kama',
        feb_mar_2026: 'Febrero – marzo 2026',
        training: 'Mesakunata wakichiy chaymanta churay',
      },
    },
    guideElector: {
      hero: {
        badge: 'Oficial Yanapay',
        title: 'Yanapay',
        titleHighlight: 'Akllaqpaq',
        description: 'Tukuy yachay munasqayki derechoykita ruwanapaq akllanapaq Piruw 2026 Hatun Akllanakuna kama. Oficial willakuy pisillapi.',
      },
      tabs: {
        general: 'Tukuy Willakuy',
        beforeVoting: 'Akllaypa Ñawpaqnin',
        votingProcess: 'Akllaypa Ruwaynin',
        fines: 'Multakuna',
        prohibitions: 'Ama Ruwanakuna',
        recommendations: 'Yuyaychaykuna',
      },
      general: {
        videoTitle: 'ONPE Yachachiy Video',
        videoSubtitle: 'Yachay imaynatachus cédula akllaypa t\'aqanapaq',
        importantBallots: 'Importante cédulakunamanta',
        importantBallotsText: 'Cédula akllaypa t\'aqakun t\'aqakunapi. Policía Nacional chaymanta Fuerzas Armadas runakunaqa huk sapalla cédulata chaskinqaku hukkunamanta hukniray.',
        whatElected: '¿Imata akllakun 2026 pi?',
        whatElectedSubtitle: 'Riqsiy ima cargokunapaq votanki',
        requirementsTitle: 'Akllaypa Munayninkunan',
        requirementsSubtitle: 'Qhaway sichus allinmi kanki yaykuypaq',
        documentsTitle: 'Allin Documentokuna',
        documentsSubtitle: 'Kay documentokuna chayllaña chaskisqa',
      },
      positions: {
        president: 'Umalliq chaymanta Vicepresidentekuna',
        presidentDesc: 'Akllakunchik Piruwpa Umalliqninta chaymanta iskay vicepresidentesninta.',
        deputies: 'Diputadokunapa Wasin',
        deputiesDesc: 'Sapa suyumanta representantekuna.',
        senators: 'Senadorkunapa Wasin',
        senatorsDesc: 'Tukuy suyupaq chaymanta suyukunapaq senadorekuna.',
        andean: 'Andes Parlamento',
        andeanDesc: 'Piruw representantekuna andes nacionkunapa organismo ñawpaqnimpi.',
      },
      requirements: {
        req1: 'Kay 18 watasniyu utaq aswan',
        req2: 'Akllaqkunapa sutinpi qillqasqa kay',
        req3: 'Piruwakunaqa akllayta atinku Piruwpi chaymanta hawa suyukunapi',
        req4: 'Akllayqa obligatorio 70 watas kama',
        req5: 'Akllayqa opcional 70 watasmanta qhipantin',
      },
      documents: {
        blueDNI: 'Anqas DNI',
        blueDNIDesc: 'Ñawpaq DNI tradicional',
        electronicDNI: 'Electrónico DNI',
        electronicDNIDesc: 'Musuq DNI chip kaqwan',
        yellowDNI: 'Q\'illu DNI',
        yellowDNIDesc: 'Hawa suyumanta tiyaqkunapaq',
        notValid: 'MANA allin',
        notValidDesc: 'Pasaporte nitaq manejay licencia',
      },
      beforeVoting: {
        whereVoteTitle: '¿Maypi Akllasaq?',
        whereVoteSubtitle: 'Tapuy maypi votanki ñawpaqmanta',
        channelsTitle: 'Tapuypa canalninkunan',
        channelsText: 'Maypi votasqaykita tapuyta atikunki kaykunapi:',
        website: 'Web p\'anqa:',
        mobileApp: 'Celular app:',
        whatsapp: 'WhatsApp:',
        whatsappText: 'ONPE tapuy yanapay',
        importantInfo: 'Importante Willakuy',
        importantInfoText: 'Maypi votasqaykita tapuptikiqa tarinki: local sutinta, mesa yupayta, orden yupayta chaymanta pabellónta. Kay willakuyta qillqay utaq pantalla fotoykita hurquy.',
        whatBringTitle: '¿Imata Apamuy Akllaypa P\'unchaynimpi?',
        whatBringSubtitle: 'Wakichiy kay imakunata lluqsiypamanta ñawpaq',
        dniRequired: 'DNI (Obligatorio)',
        dniRequiredDesc: 'DNI-yki mana pantaypaq kanman akllanapaq.',
        penOptional: 'Anqas lapicero (Opcional)',
        penOptionalDesc: 'ONPE qunman lapicerokunata, ichaqa qampa apamunki atikunki.',
        maskOptional: 'Mascarilla (Kaptinqa)',
        maskOptionalDesc: 'Sichus kanman qhali yachachiy kunan kachkan.',
      },
      votingProcess: {
        title: 'Akllaypa Ruwaynin',
        subtitle: 'Kay ruwaykunata ruway ordenpi',
        step1: 'Mesa votasqaykita tariy',
        step2: 'Cola allin ruway',
        step3: 'DNI-ykita quy mesa runaman',
        step4: 'Akllaqkunapa sutimpi firmanay',
        step5: 'Cédula akllaypa chaskiy',
        step6: 'Pakasqa cabinaman yaykuy',
        step7: 'Votaykita marcanay',
        step8: 'Cédulata ánforapi churay',
        step9: 'Mana lluqsiq tintata ruphaypi chaskiy',
        step10: 'Akllaypa constancianta chaskiy (kaptinqa)',
      },
      fines: {
        notVotingTitle: 'Multakuna Mana Akllaptiykichikqa',
        notVotingSubtitle: 'Distritokunapa clasificacionnin hina',
        extremePoor: 'Nishu waqcha',
        nonExtremePoor: 'Mana nishu waqcha',
        notPoor: 'Mana waqcha',
        memberTitle: 'Multakuna Mesa Runakunapaq',
        memberSubtitle: 'Mana ruwaykunata hunt\'aptiykichik',
        notAttend: 'Mana mesa runa hina hamuptiyki',
        leaveEarly: 'Tukupaypa ñawpaqnimpi ripuptiyki',
      },
      prohibitions: {
        title: 'Ama Ruwanakuna',
        subtitle: 'Ruwaykunaqa ama nisqakuna',
        proh1: 'Ama grabayta nitaq fotokunata hurquy cabina ukhupi',
        proh2: 'Ama votaykita hukkunaman rikuchiy',
        proh3: 'Ama propaganda akllaypa ruway localpi',
        proh4: 'Ama huk runapa sutinta suwanki',
        proh5: 'Ama partidokunapa simbolonkunawan yaykuy',
        proh6: 'Ama akllaypa localpi pantachiy',
      },
      recommendations: {
        title: 'Yuyaychaykuna',
        subtitle: 'Yuyaychay aswan allin experienciapaq',
        arriveEarly: 'Tempranuta chayamuy',
        arriveEarlyDesc: 'Ama tantanakuykunata chaymanta aswan tiempoyuq kanki.',
        checkDNI: 'DNI-ykita qhaway',
        checkDNIDesc: 'P\'unchawkuna ñawpaq qhaway sichus documentoyki allinmi.',
        noPropaganda: 'Ama propagandawan apamuy',
        noPropagandaDesc: 'Ama nisqa yaykuy símbolokunawan nitaq propaganda políticawan.',
        askHelp: 'Yanapakuyta mañakuy mana yachaspayki',
        askHelpDesc: 'Mesa runakuna yachachisuykipaq kashanku.',
        priority: 'Sapalla ñawpaqkaq',
        priorityDesc: 'Wachaq warmikuna, machukunaq chaymanta mana atikunaq runakunaq ñawpaqkaqmi.',
        checkLocation: 'Tapuy maypi votanki ñawpaqmanta',
        checkLocationDesc: 'Tariy maypi votanki p\'unchawkuna ñawpaq www.onpe.gob.pe nisqapi',
      },
    },
    dondeVotar: {
      title: '¿Maypi Akllasaq?',
      subtitle: 'Tariykuy maypi akllanayki DNI-ykiwan',
      search: {
        label: 'DNI-ykita churay (8 yupaykuna)',
        placeholder: '12345678',
        button: 'Maskay',
        searching: 'Maskachkan...',
      },
      success: 'Akllaypa centronqa tarisqa',
      errors: {
        invalidLength: 'Allin DNI 8 yupaykunayuq churay',
        onlyNumbers: 'DNI yupaykuna chayllaña',
        notFound: 'DNI-ykipaq mana willakuy tarisqachu. Yupay allinchu qhawaykuy chaymanta wakmanta ruwamuy.',
        searchError: 'Pantasqa maskaypi. Ama hina kaspa wakmanta ruwamuy.',
      },
      result: {
        votingCenter: 'Akllaypa Centro',
        fullName: 'Suti Tukuy',
        table: 'Mesa',
        district: 'Distrito',
        address: 'Maypi Kachkan',
        department: 'Suyu',
        location: 'Tarikuy',
        viewMap: 'Google Maps nisqapi qaway',
        getDirections: 'Google Maps nisqawan chayamuy',
        transport: {
          title: 'Imayna Chayamuy',
          reference: 'Yuyaychay',
          routes: 'Ñankuna kachkan',
          approxTime: 'Yaqa pacha',
          noInfo: 'Mana transporte willakuy kanchu',
        },
        schedule: {
          label: 'Akllaypa pachanta',
          time: '7:00 tutamanta - 5:00 tardeyaq',
        },
      },
      tips: {
        title: '¿Imaynatataq ruwakun?',
        step1: 'DNI yupayniykita churay (8 yupaykuna) maskaypa ukhupi',
        step2: '"Maskay" nisqapi ñit\'iy akllaypa centroykita tarinapaq',
        step3: 'Qhaway mesaykipa willakuyninta chaymanta maypi kachkanqa',
        step4: '"Ñanta Qhaway" nisqata llamk\'achiy imayna chayamunapaq yachanapaq',
      },
      infoCards: {
        instructions: {
          title: 'Akllaypa Yachachiyninkunan',
          items: [
            'DNI originalniykita apamuy chaymanta allin kachkanqa',
            'Ama política logokunauyq p\'achata churakuy',
            'Tempranuta chayamuy tantanakuykunata qhawarinaykipaq',
            'Mesa runakunapa yachachiyninkunata yupaychay',
          ],
        },
        security: {
          title: 'Waqaychakuy',
          items: [
            'Ama DNI-ykita mana riqsisqakunawan rakiy',
            'Qhaway allin centropiqchus kanki',
            'Willay ima mana allin kaptinqa autoridadkunaman',
            'Ama akllaypa centroman ama nisqa imakunata apamuy',
          ],
        },
        transport: {
          title: 'Transporte',
          publicAvailable: 'Transporte público kachkan',
          taxiAvailable: 'Taxi yanapay kachkan kay zonaykipi',
        },
      },
      quiz: {
        title: 'Akllaqkunapaq Tapukuy',
        button: 'Akllaqkunapaq Tapukuy',
        previous: 'Ñawpaq',
        next: 'Qatiq',
        questionOf: 'Tapukuy',
        of: 'manta',
        viewResults: 'Ruwaykunata qhaway',
        excellent: '¡Ancha allin! Tukuy kutichiyniykikuna allim!',
        correctAnswers: 'Allin kutichiy:',
        questions: [
          {
            question: '¿Ima documentutaq akllanaykipaq munanki?',
            options: ['Universitario carné', 'Pasaporte', 'Digital identidad', 'DNI (kunanmanta utaq pasasqa)'],
            answer: 3,
          },
          {
            question: '¿Imatataq akllaypa oficial horanqa?',
            options: ['6:00 tutamanta – 3:00 tardeyaq', '7:00 tutamanta – 5:00 tardeyaq', '8:00 tutamanta – 6:00 tardeyaq', '9:00 tutamanta – 4:00 tardeyaq'],
            answer: 1,
          },
          {
            question: '¿Imatataq mana akllaptikiqa tiyaq distritoykipi "mana waqcha"?',
            options: ['Mana multayuq', 'S/ 46 multa', 'S/ 92 multa', 'S/ 120 multa'],
            answer: 2,
          },
          {
            question: '¿Hayk\'a voto preferencialkunatataq Congresopaq markayta atikunki?',
            options: ['Mana imatapas', 'Huknin', 'Iskaynin', 'Kimsanin'],
            answer: 1,
          },
          {
            question: '¿Imatataq ruwanayki pantaspayki cédulata markaykachachkaspayki?',
            options: ['Chayllamanta quy', 'Mesa umalliqmanta musuq cédulata mañakuy', 'Localm anta lluqsiy', 'Fiscalizadorta waqyay'],
            answer: 1,
          },
        ],
      },
    },
    candidates: {
      title: 'Umalliq Akllanaman Riqkuna 2026',
      subtitle: 'Riqsiy umalliq kaypa munaqkunata',
      loading: 'Candidatokunata apamuchkan',
      filters: {
        all: 'Tukuynin',
        department: 'Suyu',
        ideology: 'Yuyaychay',
        search: 'Maskay candidatota...',
        clear: 'Filtrokunata pichay',
      },
      card: {
        viewDetails: 'Detallekunata Qhaway',
        compare: 'Tupachiy',
        party: 'Partido',
        ideology: 'Yuyaychay',
        department: 'Suyu',
      },
      noResults: 'Mana candidatokuna tarisqachu filtrokunawan akllanasqayki',
    },
    guideMembers: {
      title: 'Mesa Runakunapaq Yanapay',
      subtitle: 'Akllanakuypa p\'unchawnimpi chaniyuq willakuy',
      hero: {
        badge: 'Oficial Yanapay',
        title: 'Yanapay',
        titleHighlight: 'Mesa Runakunapaq',
        description: 'Tukuy yachay munasqayki llamk\'ayniykita hunt\'anapaq mesa runa hina Piruw 2026 Hatun Akllanakuna kama.',
      },
      tabs: {
        responsibilities: 'Ruwanakuna',
        schedule: 'Pacha',
        documents: 'Documentokuna',
        fines: 'Multakuna',
        training: 'Yachachiy',
      },
      responsibilities: {
        title: 'Ruwanakuyniykikuna',
        items: [
          'Tempranuta akllaypa localninman chayamuy',
          'Akllaqkunapa sutinta qhaway',
          'Akllaypa cédulakunata quy',
          'Akllaypa ruwayninpi qhaway',
          'Votokunata yupay tukukuypi',
          'Actakuna akllaypa firmanay',
        ],
      },
      schedule: {
        title: 'Akllaypa P\'unchaynimpi Pacha',
        arrival: 'Localman chayamuy: 6:00 tutamanta',
        opening: 'Mesa kichay: 7:00 tutamanta',
        voting: 'Akllakuy: 7:00 tutamanta - 5:00 tardeyaq',
        counting: 'Votokunata yupay: 5:00 tardeyaq qhipanmanta',
      },
      fines: {
        title: 'Mana Ruwayta Multakuna',
        notAttend: 'Mana hamuq: S/ 230',
        leaveEarly: 'Ñawpaq ripuq: S/ 230',
        excuse: 'Allin razón: Mana multa',
      },
      quiz: {
        title: 'Mesa Runakunapaq Tapukuykuna',
        previous: 'Ñawpaq',
        next: 'Qhipaman',
        showResults: 'Resultadokunata rikuy',
        perfect: '¡Allinmi! Llapa kutichiyniykikuna chiqap kanku.',
        score: 'Chiqap kutichiy',
        of: 'manta',
      },
    },
    chatbot: {
      title: 'Akllanakuypa Yanapaq',
      subtitle: 'Akllanakuna 2026',
      welcome: '¡Napaykullayki! 👋 Ñuqaqa virtual yanapaqniyki kani Piruw 2026 Akllanakuna kama. Yanapasunkim tapukuykunawan mesa runakunamanta, akllanakuypa ruwaynin, candidatokuna, chaniyuq p\'unchawkuna chaymanta aswan. ¿Imapi yanapasunkiman? 🗳️',
      placeholder: 'Qillqay tapukuyniykita akllanakuykunamanta...',
      typing: 'Qillqachkan...',
      error: 'Pampachawaykuway, pantasqa willakiykita ruwaypi. Ama hina kaspa wakmanta ruwamuy. Sichus sasachakuy qhipallampas, qhaway servidorqa llamk\'amuchtinchu.',
      helpText: 'Kaypi kachkani yanapanaykipaq akllanakuykunamanta willakuywan',
      open: 'Chatbot kichay - Virtual yanapaq akllanakuykunapaq',
      close: 'Chatbot wichqay',
    },
  },
} as const;

